import { PrismaClient } from '@prisma/client'
import { hashPassword } from '../src/lib/auth'

const prisma = new PrismaClient()

async function main() {
  console.log('Starting seed...')

  // Create categories
  const sareesCategory = await prisma.category.upsert({
    where: { slug: 'sarees' },
    update: {},
    create: {
      name: 'Sarees',
      slug: 'sarees',
      description: 'Elegant traditional sarees for every occasion',
      order: 1,
    },
  })

  const lehengasCategory = await prisma.category.upsert({
    where: { slug: 'lehengas' },
    update: {},
    create: {
      name: 'Lehengas',
      slug: 'lehengas',
      description: 'Stunning lehengas for special celebrations',
      order: 2,
    },
  })

  const kurtasCategory = await prisma.category.upsert({
    where: { slug: 'kurtas-sets' },
    update: {},
    create: {
      name: 'Kurtas & Sets',
      slug: 'kurtas-sets',
      description: 'Comfortable and stylish kurtas and sets',
      order: 3,
    },
  })

  const dupattasCategory = await prisma.category.upsert({
    where: { slug: 'dupattas-shawls' },
    update: {},
    create: {
      name: 'Dupattas & Shawls',
      slug: 'dupattas-shawls',
      description: 'Beautiful dupattas and shawls to complete your look',
      order: 4,
    },
  })

  // Create subcategories
  const silkSubcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: sareesCategory.id, slug: 'silk' } },
    update: {},
    create: {
      name: 'Silk',
      slug: 'silk',
      description: 'Luxurious silk sarees',
      categoryId: sareesCategory.id,
      order: 1,
    },
  })

  const cottonSubcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: sareesCategory.id, slug: 'cotton' } },
    update: {},
    create: {
      name: 'Cotton',
      slug: 'cotton',
      description: 'Comfortable cotton sarees',
      categoryId: sareesCategory.id,
      order: 2,
    },
  })

  const bridalSubcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: lehengasCategory.id, slug: 'bridal' } },
    update: {},
    create: {
      name: 'Bridal',
      slug: 'bridal',
      description: 'Exquisite bridal lehengas',
      categoryId: lehengasCategory.id,
      order: 1,
    },
  })

  const partySubcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: lehengasCategory.id, slug: 'party' } },
    update: {},
    create: {
      name: 'Party',
      slug: 'party',
      description: 'Stylish party lehengas',
      categoryId: lehengasCategory.id,
      order: 2,
    },
  })

  // Create admin user
  const adminPassword = await hashPassword('admin123')
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@kalyanicollections.com' },
    update: {},
    create: {
      email: 'admin@kalyanicollections.com',
      password: adminPassword,
      name: 'Admin User',
      role: 'ADMIN',
      verified: true,
    },
  })

  // Create 30 sample products
  const products = [
    // SAREES - SILK (6 products)
    {
      name: 'Royal Kanjivaram Silk Saree',
      description: 'Authentic Kanjivaram silk saree with traditional temple border and rich zari work. Perfect for weddings and grand occasions.',
      price: 35000,
      images: JSON.stringify(['/images/products/silk-saree-1.jpg', '/images/products/silk-saree-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#7c2d12', '#fbbf24']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: silkSubcategory.id,
      featured: true,
      available: true,
      stock: 5,
      sku: 'SAR-SIL-001',
      tags: JSON.stringify(['silk', 'kanjivaram', 'wedding', 'traditional', 'zari']),
    },
    {
      name: 'Banarasi Silk Saree',
      description: 'Exquisite Banarasi silk with intricate brocade work and golden zari. A timeless classic.',
      price: 28000,
      images: JSON.stringify(['/images/products/banarasi-1.jpg', '/images/products/banarasi-2.jpg']),
      colors: JSON.stringify(['#9333ea', '#dc2626', '#16a34a']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: silkSubcategory.id,
      featured: true,
      available: true,
      stock: 4,
      sku: 'SAR-SIL-002',
      tags: JSON.stringify(['silk', 'banarasi', 'brocade', 'traditional']),
    },
    {
      name: 'Tussar Silk Saree',
      description: 'Elegant tussar silk saree with hand-painted designs. Lightweight and comfortable.',
      price: 18000,
      images: JSON.stringify(['/images/products/tussar-1.jpg', '/images/products/tussar-2.jpg']),
      colors: JSON.stringify(['#fbbf24', '#ea580c', '#84cc16']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: silkSubcategory.id,
      featured: false,
      available: true,
      stock: 8,
      sku: 'SAR-SIL-003',
      tags: JSON.stringify(['silk', 'tussar', 'hand-painted', 'lightweight']),
    },
    {
      name: 'Mysore Silk Saree',
      description: 'Pure Mysore silk with elegant color combinations and fine texture.',
      price: 22000,
      images: JSON.stringify(['/images/products/mysore-1.jpg', '/images/products/mysore-2.jpg']),
      colors: JSON.stringify(['#2563eb', '#ec4899', '#16a34a']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: silkSubcategory.id,
      featured: false,
      available: true,
      stock: 6,
      sku: 'SAR-SIL-004',
      tags: JSON.stringify(['silk', 'mysore', 'pure silk', 'elegant']),
    },
    {
      name: 'Patola Silk Saree',
      description: 'Traditional double ikat Patola silk saree with geometric patterns.',
      price: 45000,
      images: JSON.stringify(['/images/products/patola-1.jpg', '/images/products/patola-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#16a34a', '#fbbf24']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: silkSubcategory.id,
      featured: true,
      available: true,
      stock: 3,
      sku: 'SAR-SIL-005',
      tags: JSON.stringify(['silk', 'patola', 'ikat', 'traditional', 'premium']),
    },
    {
      name: 'Art Silk Embroidered Saree',
      description: 'Beautiful art silk saree with contemporary embroidery and sequin work.',
      price: 12000,
      images: JSON.stringify(['/images/products/artsilk-1.jpg', '/images/products/artsilk-2.jpg']),
      colors: JSON.stringify(['#ec4899', '#9333ea', '#2563eb']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: silkSubcategory.id,
      featured: false,
      available: true,
      stock: 10,
      sku: 'SAR-SIL-006',
      tags: JSON.stringify(['silk', 'art silk', 'embroidered', 'contemporary']),
    },

    // SAREES - COTTON (5 products)
    {
      name: 'Handloom Cotton Saree',
      description: 'Pure handloom cotton saree perfect for daily wear. Breathable and comfortable.',
      price: 2500,
      images: JSON.stringify(['/images/products/cotton-1.jpg', '/images/products/cotton-2.jpg']),
      colors: JSON.stringify(['#16a34a', '#2563eb', '#dc2626']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: cottonSubcategory.id,
      featured: false,
      available: true,
      stock: 15,
      sku: 'SAR-COT-001',
      tags: JSON.stringify(['cotton', 'handloom', 'daily wear', 'comfortable']),
    },
    {
      name: 'Bengal Cotton Tant Saree',
      description: 'Traditional Bengal tant cotton saree with classic border design.',
      price: 3200,
      images: JSON.stringify(['/images/products/tant-1.jpg', '/images/products/tant-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#fbbf24', '#16a34a']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: cottonSubcategory.id,
      featured: false,
      available: true,
      stock: 12,
      sku: 'SAR-COT-002',
      tags: JSON.stringify(['cotton', 'tant', 'bengal', 'traditional']),
    },
    {
      name: 'Block Print Cotton Saree',
      description: 'Handblock printed cotton saree with natural dyes. Eco-friendly and stylish.',
      price: 2800,
      images: JSON.stringify(['/images/products/blockprint-1.jpg', '/images/products/blockprint-2.jpg']),
      colors: JSON.stringify(['#ea580c', '#84cc16', '#2563eb']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: cottonSubcategory.id,
      featured: false,
      available: true,
      stock: 10,
      sku: 'SAR-COT-003',
      tags: JSON.stringify(['cotton', 'block print', 'handblock', 'eco-friendly']),
    },
    {
      name: 'Mangalgiri Cotton Saree',
      description: 'Soft Mangalgiri cotton with contrast border. Perfect for office wear.',
      price: 2200,
      images: JSON.stringify(['/images/products/mangalgiri-1.jpg', '/images/products/mangalgiri-2.jpg']),
      colors: JSON.stringify(['#2563eb', '#16a34a', '#ec4899']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: cottonSubcategory.id,
      featured: false,
      available: true,
      stock: 18,
      sku: 'SAR-COT-004',
      tags: JSON.stringify(['cotton', 'mangalgiri', 'office wear', 'soft']),
    },
    {
      name: 'Khadi Cotton Saree',
      description: 'Pure khadi cotton saree supporting local artisans. Simple and elegant.',
      price: 3500,
      images: JSON.stringify(['/images/products/khadi-1.jpg', '/images/products/khadi-2.jpg']),
      colors: JSON.stringify(['#fbbf24', '#16a34a', '#dc2626']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: sareesCategory.id,
      subcategoryId: cottonSubcategory.id,
      featured: false,
      available: true,
      stock: 8,
      sku: 'SAR-COT-005',
      tags: JSON.stringify(['cotton', 'khadi', 'handspun', 'artisan']),
    },

    // LEHENGAS - BRIDAL (5 products)
    {
      name: 'Grand Bridal Lehenga',
      description: 'Stunning bridal lehenga with heavy zardozi work and Swarovski crystals. Make your wedding unforgettable.',
      price: 85000,
      images: JSON.stringify(['/images/products/bridal-1.jpg', '/images/products/bridal-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#fbbf24', '#9333ea']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: bridalSubcategory.id,
      featured: true,
      available: true,
      stock: 2,
      sku: 'LEH-BRI-001',
      tags: JSON.stringify(['bridal', 'zardozi', 'crystal', 'wedding', 'premium']),
    },
    {
      name: 'Royal Velvet Bridal Lehenga',
      description: 'Luxurious velvet bridal lehenga with antique gold embroidery.',
      price: 95000,
      images: JSON.stringify(['/images/products/velvet-bridal-1.jpg', '/images/products/velvet-bridal-2.jpg']),
      colors: JSON.stringify(['#7c2d12', '#dc2626', '#16a34a']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: bridalSubcategory.id,
      featured: true,
      available: true,
      stock: 3,
      sku: 'LEH-BRI-002',
      tags: JSON.stringify(['bridal', 'velvet', 'luxury', 'embroidery']),
    },
    {
      name: 'Designer Bridal Lehenga Set',
      description: 'Contemporary bridal lehenga with mirror work and thread embroidery.',
      price: 75000,
      images: JSON.stringify(['/images/products/designer-bridal-1.jpg', '/images/products/designer-bridal-2.jpg']),
      colors: JSON.stringify(['#ec4899', '#9333ea', '#fbbf24']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: bridalSubcategory.id,
      featured: true,
      available: true,
      stock: 4,
      sku: 'LEH-BRI-003',
      tags: JSON.stringify(['bridal', 'designer', 'mirror work', 'contemporary']),
    },
    {
      name: 'Traditional Red Bridal Lehenga',
      description: 'Classic red bridal lehenga with intricate gota patti work.',
      price: 68000,
      images: JSON.stringify(['/images/products/red-bridal-1.jpg', '/images/products/red-bridal-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#fbbf24']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: bridalSubcategory.id,
      featured: false,
      available: true,
      stock: 5,
      sku: 'LEH-BRI-004',
      tags: JSON.stringify(['bridal', 'red', 'traditional', 'gota patti']),
    },
    {
      name: 'Pastel Bridal Lehenga',
      description: 'Modern pastel bridal lehenga with delicate floral embroidery.',
      price: 72000,
      images: JSON.stringify(['/images/products/pastel-bridal-1.jpg', '/images/products/pastel-bridal-2.jpg']),
      colors: JSON.stringify(['#fbbf24', '#ec4899', '#84cc16']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: bridalSubcategory.id,
      featured: false,
      available: true,
      stock: 4,
      sku: 'LEH-BRI-005',
      tags: JSON.stringify(['bridal', 'pastel', 'modern', 'floral']),
    },

    // LEHENGAS - PARTY (4 products)
    {
      name: 'Sequin Party Lehenga',
      description: 'Glamorous sequin lehenga perfect for cocktail parties and celebrations.',
      price: 18000,
      images: JSON.stringify(['/images/products/sequin-party-1.jpg', '/images/products/sequin-party-2.jpg']),
      colors: JSON.stringify(['#ec4899', '#2563eb', '#fbbf24']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: partySubcategory.id,
      featured: false,
      available: true,
      stock: 8,
      sku: 'LEH-PAR-001',
      tags: JSON.stringify(['party', 'sequin', 'glamorous', 'cocktail']),
    },
    {
      name: 'Indo-Western Party Lehenga',
      description: 'Trendy indo-western lehenga with crop top and jacket.',
      price: 22000,
      images: JSON.stringify(['/images/products/indowestern-1.jpg', '/images/products/indowestern-2.jpg']),
      colors: JSON.stringify(['#2563eb', '#16a34a', '#ec4899']),
      sizes: JSON.stringify(['S', 'M', 'L']),
      categoryId: lehengasCategory.id,
      subcategoryId: partySubcategory.id,
      featured: false,
      available: true,
      stock: 6,
      sku: 'LEH-PAR-002',
      tags: JSON.stringify(['party', 'indo-western', 'trendy', 'crop top']),
    },
    {
      name: 'Georgette Party Lehenga',
      description: 'Flowy georgette lehenga with contemporary print and embellishments.',
      price: 15000,
      images: JSON.stringify(['/images/products/georgette-party-1.jpg', '/images/products/georgette-party-2.jpg']),
      colors: JSON.stringify(['#9333ea', '#ec4899', '#2563eb']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: lehengasCategory.id,
      subcategoryId: partySubcategory.id,
      featured: false,
      available: true,
      stock: 10,
      sku: 'LEH-PAR-003',
      tags: JSON.stringify(['party', 'georgette', 'flowy', 'contemporary']),
    },
    {
      name: 'Net Party Lehenga',
      description: 'Elegant net lehenga with stone work and pearl detailing.',
      price: 20000,
      images: JSON.stringify(['/images/products/net-party-1.jpg', '/images/products/net-party-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#16a34a', '#fbbf24']),
      sizes: JSON.stringify(['S', 'M', 'L']),
      categoryId: lehengasCategory.id,
      subcategoryId: partySubcategory.id,
      featured: false,
      available: true,
      stock: 7,
      sku: 'LEH-PAR-004',
      tags: JSON.stringify(['party', 'net', 'stone work', 'pearl']),
    },

    // KURTAS & SETS (5 products)
    {
      name: 'Anarkali Kurta Set',
      description: 'Elegant anarkali kurta with palazzo and dupatta. Perfect for festive occasions.',
      price: 5500,
      images: JSON.stringify(['/images/products/anarkali-1.jpg', '/images/products/anarkali-2.jpg']),
      colors: JSON.stringify(['#16a34a', '#2563eb', '#ec4899']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
      categoryId: kurtasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 12,
      sku: 'KUR-SET-001',
      tags: JSON.stringify(['kurta', 'anarkali', 'festive', 'palazzo']),
    },
    {
      name: 'Straight Cut Kurta Set',
      description: 'Contemporary straight cut kurta with pants and dupatta. Ideal for office wear.',
      price: 3800,
      images: JSON.stringify(['/images/products/straight-kurta-1.jpg', '/images/products/straight-kurta-2.jpg']),
      colors: JSON.stringify(['#2563eb', '#16a34a', '#dc2626']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
      categoryId: kurtasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 15,
      sku: 'KUR-SET-002',
      tags: JSON.stringify(['kurta', 'straight cut', 'office wear', 'contemporary']),
    },
    {
      name: 'Ethnic Cotton Kurta',
      description: 'Comfortable cotton kurta with traditional prints. Great for casual wear.',
      price: 2200,
      images: JSON.stringify(['/images/products/cotton-kurta-1.jpg', '/images/products/cotton-kurta-2.jpg']),
      colors: JSON.stringify(['#fbbf24', '#16a34a', '#2563eb']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
      categoryId: kurtasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 20,
      sku: 'KUR-SET-003',
      tags: JSON.stringify(['kurta', 'cotton', 'casual', 'prints']),
    },
    {
      name: 'Chanderi Kurta Set',
      description: 'Luxurious chanderi kurta with zari work and matching bottom.',
      price: 6500,
      images: JSON.stringify(['/images/products/chanderi-kurta-1.jpg', '/images/products/chanderi-kurta-2.jpg']),
      colors: JSON.stringify(['#ec4899', '#9333ea', '#fbbf24']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL']),
      categoryId: kurtasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 8,
      sku: 'KUR-SET-004',
      tags: JSON.stringify(['kurta', 'chanderi', 'zari', 'luxury']),
    },
    {
      name: 'Palazzo Kurta Set',
      description: 'Trendy kurta with wide palazzo pants and printed dupatta.',
      price: 4200,
      images: JSON.stringify(['/images/products/palazzo-kurta-1.jpg', '/images/products/palazzo-kurta-2.jpg']),
      colors: JSON.stringify(['#16a34a', '#dc2626', '#2563eb']),
      sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
      categoryId: kurtasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 14,
      sku: 'KUR-SET-005',
      tags: JSON.stringify(['kurta', 'palazzo', 'trendy', 'printed']),
    },

    // DUPATTAS & SHAWLS (5 products)
    {
      name: 'Banarasi Silk Dupatta',
      description: 'Elegant Banarasi silk dupatta with golden zari work.',
      price: 3500,
      images: JSON.stringify(['/images/products/banarasi-dupatta-1.jpg', '/images/products/banarasi-dupatta-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#16a34a', '#fbbf24']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: dupattasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 15,
      sku: 'DUP-SIL-001',
      tags: JSON.stringify(['dupatta', 'banarasi', 'silk', 'zari']),
    },
    {
      name: 'Phulkari Dupatta',
      description: 'Traditional Phulkari embroidered dupatta from Punjab.',
      price: 2800,
      images: JSON.stringify(['/images/products/phulkari-1.jpg', '/images/products/phulkari-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#fbbf24', '#16a34a']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: dupattasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 12,
      sku: 'DUP-PHU-001',
      tags: JSON.stringify(['dupatta', 'phulkari', 'embroidered', 'punjab']),
    },
    {
      name: 'Chiffon Dupatta',
      description: 'Lightweight chiffon dupatta with delicate embroidery.',
      price: 1500,
      images: JSON.stringify(['/images/products/chiffon-dupatta-1.jpg', '/images/products/chiffon-dupatta-2.jpg']),
      colors: JSON.stringify(['#ec4899', '#2563eb', '#16a34a']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: dupattasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 25,
      sku: 'DUP-CHI-001',
      tags: JSON.stringify(['dupatta', 'chiffon', 'lightweight', 'embroidery']),
    },
    {
      name: 'Pashmina Shawl',
      description: 'Luxurious pashmina shawl for warmth and elegance.',
      price: 8500,
      images: JSON.stringify(['/images/products/pashmina-1.jpg', '/images/products/pashmina-2.jpg']),
      colors: JSON.stringify(['#7c2d12', '#16a34a', '#2563eb']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: dupattasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 6,
      sku: 'SHA-PAS-001',
      tags: JSON.stringify(['shawl', 'pashmina', 'luxury', 'warm']),
    },
    {
      name: 'Bandhani Dupatta',
      description: 'Colorful bandhani tie-dye dupatta from Rajasthan.',
      price: 1800,
      images: JSON.stringify(['/images/products/bandhani-1.jpg', '/images/products/bandhani-2.jpg']),
      colors: JSON.stringify(['#dc2626', '#fbbf24', '#16a34a', '#2563eb']),
      sizes: JSON.stringify(['Free Size']),
      categoryId: dupattasCategory.id,
      subcategoryId: null,
      featured: false,
      available: true,
      stock: 20,
      sku: 'DUP-BAN-001',
      tags: JSON.stringify(['dupatta', 'bandhani', 'tie-dye', 'rajasthan', 'colorful']),
    },
  ]

  for (const product of products) {
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: {},
      create: product,
    })
  }

  // Create site settings
  const settings = [
    { key: 'site_name', value: 'Kalyani Collections', description: 'Site name' },
    { key: 'site_description', value: 'Your trusted boutique for authentic Indian wear', description: 'Site description' },
    { key: 'contact_email', value: 'info@kalyanicollections.com', description: 'Contact email' },
    { key: 'contact_phone', value: '+91 99647 42910', description: 'Contact phone' },
    { key: 'address', value: '#40, 1st Main Rd, Basaveshwar Nagar, Bengaluru, Karnataka 560079', description: 'Store address' },
  ]

  for (const setting of settings) {
    await prisma.siteSettings.upsert({
      where: { key: setting.key },
      update: {},
      create: setting,
    })
  }

  console.log('Seed completed successfully!')
  console.log('✅ Created 30 products across all categories')
  console.log('✅ Admin user: admin@kalyanicollections.com / admin123')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })